# service.yaml content
apiVersion: v1
kind: Service
metadata:
  name: myshopifyapp-service
spec:
  selector:
    app: myshopifyapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
